# Spring Boot read this, it configures how Spring boot connect PostgreSQL
spring.application.name=incident-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/incident_platform
spring.datasource.username=incident_app
spring.datasource.password=incident_app_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
